### ISSUE TITLE
Import error with Python 2.5

### ISSUE THREAD

**Issue by ryanbagwell** [matthewwithanm/django-classbasedsettings#13]
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/var/virtualenvs/topoftherocknyc.com/lib/python2.5/site-packages/cbsettings/__init__.py", line 9
    from .version import *
SyntaxError: 'import *' not allowed with 'from .'
```

**Comment by ryanbagwell** [comment]
I'll fork and create a pull request tomorrow.

**Comment by matthewwithanm** [comment]
Yeah, I wasn't really planning on 2.5 support. (Just [been testing](https://github.com/matthewwithanm/django-classbasedsettings/blob/develop/.travis.yml) for 2.6 and 2.7.) I guess if that's the only issue though we can change it to an absolute import.
