### ISSUE TITLE
Question: how to integrate with celery?

### ISSUE THREAD

**Issue by rrauenza** [matthewwithanm/django-classbasedsettings#20]
Is there a known way with making this work with celery when integrated with Django?

django-configurations seems to have a workaround, but when I try something similar, I think I'm getting circular import problems.  Still trying to track it down ...

**Comment by rrauenza** [comment]
The problem is [celery docs instruct](http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html) integration this way:
- Modify mysite/__init__.py to import "app" as "celery_app" from mysite.celery - This makes the celery "app" available for django at mysite.celery_app.
- Add mysite/celery.py that imports settings.conf from django.conf, and sets DJANGO_SETTINGS_MODULE.  This initializes django into celery command line tools. 

I think he problem is I that mysite.__init__ gets implicitly loaded during cbsetting's intiialization, which then tries to do cbsettings again.

edit: [I think I've solved the issue.  Will report after verifying through more testing.]

**Comment by rrauenza** [comment]
Ok, the problem appeared to be a mistyped class name.

What seems to work is to follow the celery instructions for integration, along with the cbsettings, but in mysite/celery.py just do something like this:

```
from __future__ import absolute_import
from celery import Celery

# set the default Django settings module for the 'celery' program.
# import os
# os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'mysite.settings')

import cbsettings
cbsettings.configure('mysite.config.factory')

from django.conf import settings  # noqa

app = Celery('mysite')

# Using a string here means the worker will not have to
# pickle the object when using Windows.
app.config_from_object(settings.CELERY_CONFIG)
app.autodiscover_tasks(lambda: settings.INSTALLED_APPS)


@app.task(bind=True)
def debug_task(self):
    print('Request: {0!r}'.format(self.request))
```

**Comment by RevolutionTech** [comment]
Sorry I didn't get a chance to look into this but I'm glad you figured it out. Hopefully it will help someone else running into Celery issues in the future!

**Comment by rrauenza** [comment]
No problem -- it was just PIBKAC, but I thought I would document it here anyway.
