### ISSUE TITLE
FOO = Class gets instantiated

### ISSUE THREAD

**Issue by rrauenza** [matthewwithanm/django-classbasedsettings#23]
FOO=Class is a callable ... so Class gets called and instantiated into an object even though I really want the class instead.

Is there a workaround?  Do I just need to make a lambda that returns the class?

**Comment by RevolutionTech** [comment]
Is this for your own custom setting? With Django it is more idiomatic to make settings that refer to classes by name.

**Comment by rrauenza** [comment]
@RevolutionTech It's for a django_filters setting.

```
from django_filters import STRICTNESS
[...]
    FILTERS_STRICTNESS = STRICTNESS.RAISE_VALIDATION_ERROR
```

**Comment by RevolutionTech** [comment]
Ah bummer, I think the simplest workaround would be what you suggested, which is to provide a lambda that returns the value you're interested in.

FWIW though in `django_filters` 2.0, the `FILTERS_STRICTNESS` setting was deprecated in favour of moving strictness to views.

**Comment by rrauenza** [comment]
@RevolutionTech I could imagine maybe adding something like this to the project,

```
class Constant(object):                                                          
                                                                                 
    def __init__(self, value):                                                   
        self.value = value                                                       
                                                                                 
    def __call__(self):                                                          
        return self.value                                                        
                                                                                                                                                                  
print Constant("Fooooo")()                       
```

Then it would be  

```
FILTERS_STRICTNESS = Constant(STRICTNESS.RAISE_VALIDATION_ERROR)
```
Although if I could go back in time, I'd suggest `Callable()` instead to mark callables and assume constants otherwise.
